import type { PhaseCategories } from '@/lib/game/types';
import type { GameSize } from '@/lib/game/types';

// ============================================================
// Engine Feature System
// ============================================================

export type EngineFeatureCategory = keyof PhaseCategories;

export interface EngineFeatureDef {
  id: string;
  name: string;
  category: EngineFeatureCategory;
  group: string;
  tier: number;
  researchCost: { rp: number; money: number };
  engineCost: number;
  gameCostBySize: Record<GameSize, number>;
  devPointsAdded: number;
  benefitScore: number;
  prerequisites: string[];
  startsUnlocked: boolean;
}

// ============================================================
// Feature Catalog
// ============================================================

export const ENGINE_FEATURES: EngineFeatureDef[] = [
  // ----------------------------------------------------------
  // Graphics
  // ----------------------------------------------------------
  {
    id: 'text-based',
    name: 'Text-Based',
    category: 'graphics',
    group: 'gfx-core',
    tier: 0,
    researchCost: { rp: 0, money: 0 },
    engineCost: 5_000,
    gameCostBySize: { small: 0, medium: 0, large: 0, mmorpg: 0 },
    devPointsAdded: 0,
    benefitScore: 0,
    prerequisites: [],
    startsUnlocked: true,
  },
  {
    id: '2d-v1',
    name: '2D Graphics V1',
    category: 'graphics',
    group: 'gfx-core',
    tier: 1,
    researchCost: { rp: 0, money: 0 },
    engineCost: 10_000,
    gameCostBySize: { small: 0, medium: 0, large: 0, mmorpg: 0 },
    devPointsAdded: 5,
    benefitScore: 2,
    prerequisites: [],
    startsUnlocked: true,
  },
  {
    id: '2d-v2',
    name: '2D Graphics V2',
    category: 'graphics',
    group: 'gfx-core',
    tier: 2,
    researchCost: { rp: 0, money: 50_000 },
    engineCost: 30_000,
    gameCostBySize: { small: 30_000, medium: 60_000, large: 90_000, mmorpg: 180_000 },
    devPointsAdded: 10,
    benefitScore: 4,
    prerequisites: ['2d-v1'],
    startsUnlocked: false,
  },
  {
    id: '2d-v3',
    name: '2D Graphics V3',
    category: 'graphics',
    group: 'gfx-core',
    tier: 3,
    researchCost: { rp: 80, money: 240_000 },
    engineCost: 100_000,
    gameCostBySize: { small: 60_000, medium: 120_000, large: 180_000, mmorpg: 360_000 },
    devPointsAdded: 15,
    benefitScore: 6,
    prerequisites: ['2d-v2'],
    startsUnlocked: false,
  },
  {
    id: '2d-v4',
    name: '2D Graphics V4',
    category: 'graphics',
    group: 'gfx-core',
    tier: 4,
    researchCost: { rp: 100, money: 400_000 },
    engineCost: 140_000,
    gameCostBySize: { small: 100_000, medium: 200_000, large: 300_000, mmorpg: 600_000 },
    devPointsAdded: 20,
    benefitScore: 8,
    prerequisites: ['2d-v3'],
    startsUnlocked: false,
  },
  {
    id: '2d-v5',
    name: '2D Graphics V5',
    category: 'graphics',
    group: 'gfx-core',
    tier: 5,
    researchCost: { rp: 150, money: 600_000 },
    engineCost: 180_000,
    gameCostBySize: { small: 150_000, medium: 300_000, large: 450_000, mmorpg: 900_000 },
    devPointsAdded: 25,
    benefitScore: 10,
    prerequisites: ['2d-v4'],
    startsUnlocked: false,
  },
  {
    id: '3d-v1',
    name: '3D Graphics V1',
    category: 'graphics',
    group: 'gfx-core',
    tier: 6,
    researchCost: { rp: 15, money: 40_000 },
    engineCost: 30_000,
    gameCostBySize: { small: 10_000, medium: 20_000, large: 30_000, mmorpg: 60_000 },
    devPointsAdded: 10,
    benefitScore: 2,
    prerequisites: ['2d-v2'],
    startsUnlocked: false,
  },
  {
    id: '3d-v2',
    name: '3D Graphics V2',
    category: 'graphics',
    group: 'gfx-core',
    tier: 7,
    researchCost: { rp: 40, money: 120_000 },
    engineCost: 50_000,
    gameCostBySize: { small: 30_000, medium: 60_000, large: 90_000, mmorpg: 180_000 },
    devPointsAdded: 15,
    benefitScore: 4,
    prerequisites: ['3d-v1'],
    startsUnlocked: false,
  },
  {
    id: '3d-v3',
    name: '3D Graphics V3',
    category: 'graphics',
    group: 'gfx-core',
    tier: 8,
    researchCost: { rp: 80, money: 240_000 },
    engineCost: 100_000,
    gameCostBySize: { small: 60_000, medium: 120_000, large: 180_000, mmorpg: 360_000 },
    devPointsAdded: 20,
    benefitScore: 6,
    prerequisites: ['3d-v2'],
    startsUnlocked: false,
  },
  {
    id: '3d-v4',
    name: '3D Graphics V4',
    category: 'graphics',
    group: 'gfx-core',
    tier: 9,
    researchCost: { rp: 100, money: 400_000 },
    engineCost: 140_000,
    gameCostBySize: { small: 100_000, medium: 200_000, large: 300_000, mmorpg: 600_000 },
    devPointsAdded: 25,
    benefitScore: 8,
    prerequisites: ['3d-v3'],
    startsUnlocked: false,
  },
  {
    id: '3d-v5',
    name: '3D Graphics V5',
    category: 'graphics',
    group: 'gfx-core',
    tier: 10,
    researchCost: { rp: 150, money: 600_000 },
    engineCost: 180_000,
    gameCostBySize: { small: 150_000, medium: 300_000, large: 450_000, mmorpg: 900_000 },
    devPointsAdded: 30,
    benefitScore: 10,
    prerequisites: ['3d-v4'],
    startsUnlocked: false,
  },
  {
    id: '3d-v6',
    name: '3D Graphics V6',
    category: 'graphics',
    group: 'gfx-core',
    tier: 11,
    researchCost: { rp: 250, money: 1_200_000 },
    engineCost: 350_000,
    gameCostBySize: { small: 300_000, medium: 600_000, large: 900_000, mmorpg: 1_800_000 },
    devPointsAdded: 35,
    benefitScore: 12,
    prerequisites: ['3d-v5'],
    startsUnlocked: false,
  },
  {
    id: '3d-v7',
    name: '3D Graphics V7',
    category: 'graphics',
    group: 'gfx-core',
    tier: 12,
    researchCost: { rp: 300, money: 1_600_000 },
    engineCost: 500_000,
    gameCostBySize: { small: 400_000, medium: 800_000, large: 1_200_000, mmorpg: 2_400_000 },
    devPointsAdded: 40,
    benefitScore: 14,
    prerequisites: ['3d-v6'],
    startsUnlocked: false,
  },
  {
    id: 'stereoscopic-3d',
    name: 'Stereoscopic 3D',
    category: 'graphics',
    group: 'gfx-stereo',
    tier: 1,
    researchCost: { rp: 40, money: 120_000 },
    engineCost: 50_000,
    gameCostBySize: { small: 30_000, medium: 60_000, large: 90_000, mmorpg: 180_000 },
    devPointsAdded: 10,
    benefitScore: 4,
    prerequisites: ['3d-v1'],
    startsUnlocked: false,
  },

  // ----------------------------------------------------------
  // Sound
  // ----------------------------------------------------------
  {
    id: 'basic-sound',
    name: 'Basic Sound',
    category: 'sound',
    group: 'sound-core',
    tier: 0,
    researchCost: { rp: 0, money: 0 },
    engineCost: 5_000,
    gameCostBySize: { small: 0, medium: 0, large: 0, mmorpg: 0 },
    devPointsAdded: 0,
    benefitScore: 0,
    prerequisites: [],
    startsUnlocked: true,
  },
  {
    id: 'mono-sound',
    name: 'Mono Sound',
    category: 'sound',
    group: 'sound-core',
    tier: 1,
    researchCost: { rp: 15, money: 40_000 },
    engineCost: 30_000,
    gameCostBySize: { small: 10_000, medium: 20_000, large: 30_000, mmorpg: 60_000 },
    devPointsAdded: 5,
    benefitScore: 2,
    prerequisites: ['basic-sound'],
    startsUnlocked: false,
  },
  {
    id: 'stereo-sound',
    name: 'Stereo Sound',
    category: 'sound',
    group: 'sound-core',
    tier: 2,
    researchCost: { rp: 40, money: 120_000 },
    engineCost: 50_000,
    gameCostBySize: { small: 30_000, medium: 60_000, large: 90_000, mmorpg: 180_000 },
    devPointsAdded: 10,
    benefitScore: 4,
    prerequisites: ['mono-sound'],
    startsUnlocked: false,
  },
  {
    id: 'soundtrack',
    name: 'Soundtrack',
    category: 'sound',
    group: 'sound-music',
    tier: 1,
    researchCost: { rp: 40, money: 120_000 },
    engineCost: 50_000,
    gameCostBySize: { small: 30_000, medium: 60_000, large: 90_000, mmorpg: 180_000 },
    devPointsAdded: 8,
    benefitScore: 4,
    prerequisites: ['mono-sound'],
    startsUnlocked: false,
  },
  {
    id: 'surround-sound',
    name: 'Surround Sound',
    category: 'sound',
    group: 'sound-core',
    tier: 3,
    researchCost: { rp: 80, money: 240_000 },
    engineCost: 100_000,
    gameCostBySize: { small: 60_000, medium: 120_000, large: 180_000, mmorpg: 360_000 },
    devPointsAdded: 15,
    benefitScore: 6,
    prerequisites: ['stereo-sound'],
    startsUnlocked: false,
  },
  {
    id: 'orchestral-soundtrack',
    name: 'Orchestral Soundtrack',
    category: 'sound',
    group: 'sound-music',
    tier: 2,
    researchCost: { rp: 100, money: 400_000 },
    engineCost: 140_000,
    gameCostBySize: { small: 100_000, medium: 200_000, large: 300_000, mmorpg: 600_000 },
    devPointsAdded: 20,
    benefitScore: 8,
    prerequisites: ['soundtrack'],
    startsUnlocked: false,
  },

  // ----------------------------------------------------------
  // Story/Quests
  // ----------------------------------------------------------
  {
    id: 'linear-story',
    name: 'Linear Story',
    category: 'storyQuests',
    group: 'story-core',
    tier: 1,
    researchCost: { rp: 0, money: 0 },
    engineCost: 30_000,
    gameCostBySize: { small: 10_000, medium: 20_000, large: 30_000, mmorpg: 60_000 },
    devPointsAdded: 5,
    benefitScore: 2,
    prerequisites: [],
    startsUnlocked: true,
  },
  {
    id: 'simple-cutscenes',
    name: 'Simple Cutscenes',
    category: 'storyQuests',
    group: 'story-cutscenes',
    tier: 1,
    researchCost: { rp: 15, money: 40_000 },
    engineCost: 30_000,
    gameCostBySize: { small: 10_000, medium: 20_000, large: 30_000, mmorpg: 60_000 },
    devPointsAdded: 5,
    benefitScore: 2,
    prerequisites: ['linear-story'],
    startsUnlocked: false,
  },
  {
    id: 'branching-story',
    name: 'Branching Story',
    category: 'storyQuests',
    group: 'story-core',
    tier: 2,
    researchCost: { rp: 40, money: 120_000 },
    engineCost: 50_000,
    gameCostBySize: { small: 30_000, medium: 60_000, large: 90_000, mmorpg: 180_000 },
    devPointsAdded: 10,
    benefitScore: 4,
    prerequisites: ['linear-story'],
    startsUnlocked: false,
  },
  {
    id: 'advanced-cutscenes',
    name: 'Advanced Cutscenes',
    category: 'storyQuests',
    group: 'story-cutscenes',
    tier: 2,
    researchCost: { rp: 40, money: 120_000 },
    engineCost: 50_000,
    gameCostBySize: { small: 30_000, medium: 60_000, large: 90_000, mmorpg: 180_000 },
    devPointsAdded: 10,
    benefitScore: 4,
    prerequisites: ['simple-cutscenes'],
    startsUnlocked: false,
  },
  {
    id: 'full-motion-video',
    name: 'Full Motion Video',
    category: 'storyQuests',
    group: 'story-fmv',
    tier: 1,
    researchCost: { rp: 80, money: 240_000 },
    engineCost: 100_000,
    gameCostBySize: { small: 60_000, medium: 120_000, large: 180_000, mmorpg: 360_000 },
    devPointsAdded: 15,
    benefitScore: 6,
    prerequisites: ['advanced-cutscenes'],
    startsUnlocked: false,
  },
  {
    id: 'interactive-story',
    name: 'Interactive Story',
    category: 'storyQuests',
    group: 'story-core',
    tier: 3,
    researchCost: { rp: 80, money: 240_000 },
    engineCost: 100_000,
    gameCostBySize: { small: 60_000, medium: 120_000, large: 180_000, mmorpg: 360_000 },
    devPointsAdded: 15,
    benefitScore: 6,
    prerequisites: ['branching-story'],
    startsUnlocked: false,
  },
  {
    id: 'moral-choices',
    name: 'Moral Choices',
    category: 'storyQuests',
    group: 'story-choices',
    tier: 1,
    researchCost: { rp: 80, money: 240_000 },
    engineCost: 100_000,
    gameCostBySize: { small: 60_000, medium: 120_000, large: 180_000, mmorpg: 360_000 },
    devPointsAdded: 15,
    benefitScore: 6,
    prerequisites: ['branching-story'],
    startsUnlocked: false,
  },
  {
    id: 'immersive-storytelling',
    name: 'Immersive Storytelling',
    category: 'storyQuests',
    group: 'story-core',
    tier: 4,
    researchCost: { rp: 100, money: 400_000 },
    engineCost: 140_000,
    gameCostBySize: { small: 100_000, medium: 200_000, large: 300_000, mmorpg: 600_000 },
    devPointsAdded: 20,
    benefitScore: 8,
    prerequisites: ['interactive-story'],
    startsUnlocked: false,
  },
  {
    id: 'reactive-quests',
    name: 'Reactive Quests',
    category: 'storyQuests',
    group: 'story-quests',
    tier: 1,
    researchCost: { rp: 150, money: 600_000 },
    engineCost: 180_000,
    gameCostBySize: { small: 150_000, medium: 300_000, large: 450_000, mmorpg: 900_000 },
    devPointsAdded: 25,
    benefitScore: 10,
    prerequisites: ['immersive-storytelling'],
    startsUnlocked: false,
  },

  // ----------------------------------------------------------
  // Engine (core tech)
  // ----------------------------------------------------------
  {
    id: 'save-game',
    name: 'Save Game',
    category: 'engine',
    group: 'engine-save',
    tier: 1,
    researchCost: { rp: 0, money: 0 },
    engineCost: 10_000,
    gameCostBySize: { small: 5_000, medium: 10_000, large: 15_000, mmorpg: 30_000 },
    devPointsAdded: 3,
    benefitScore: 1,
    prerequisites: [],
    startsUnlocked: true,
  },
  {
    id: 'multiplayer',
    name: 'Multiplayer',
    category: 'engine',
    group: 'engine-multiplayer',
    tier: 1,
    researchCost: { rp: 15, money: 40_000 },
    engineCost: 30_000,
    gameCostBySize: { small: 10_000, medium: 20_000, large: 30_000, mmorpg: 60_000 },
    devPointsAdded: 8,
    benefitScore: 2,
    prerequisites: ['save-game'],
    startsUnlocked: false,
  },
  {
    id: 'video-playback',
    name: 'Video Playback',
    category: 'engine',
    group: 'engine-video',
    tier: 1,
    researchCost: { rp: 40, money: 120_000 },
    engineCost: 50_000,
    gameCostBySize: { small: 30_000, medium: 60_000, large: 90_000, mmorpg: 180_000 },
    devPointsAdded: 10,
    benefitScore: 4,
    prerequisites: ['save-game'],
    startsUnlocked: false,
  },
  {
    id: 'basic-physics',
    name: 'Basic Physics',
    category: 'engine',
    group: 'engine-physics',
    tier: 1,
    researchCost: { rp: 40, money: 120_000 },
    engineCost: 50_000,
    gameCostBySize: { small: 30_000, medium: 60_000, large: 90_000, mmorpg: 180_000 },
    devPointsAdded: 10,
    benefitScore: 4,
    prerequisites: ['save-game'],
    startsUnlocked: false,
  },
  {
    id: 'mod-support',
    name: 'Mod Support',
    category: 'engine',
    group: 'engine-modding',
    tier: 1,
    researchCost: { rp: 15, money: 40_000 },
    engineCost: 30_000,
    gameCostBySize: { small: 10_000, medium: 20_000, large: 30_000, mmorpg: 60_000 },
    devPointsAdded: 5,
    benefitScore: 2,
    prerequisites: ['save-game'],
    startsUnlocked: false,
  },
  {
    id: 'online-play',
    name: 'Online Play',
    category: 'engine',
    group: 'engine-multiplayer',
    tier: 2,
    researchCost: { rp: 80, money: 240_000 },
    engineCost: 100_000,
    gameCostBySize: { small: 60_000, medium: 120_000, large: 180_000, mmorpg: 360_000 },
    devPointsAdded: 15,
    benefitScore: 6,
    prerequisites: ['multiplayer'],
    startsUnlocked: false,
  },
  {
    id: 'advanced-physics',
    name: 'Advanced Physics',
    category: 'engine',
    group: 'engine-physics',
    tier: 2,
    researchCost: { rp: 100, money: 400_000 },
    engineCost: 140_000,
    gameCostBySize: { small: 100_000, medium: 200_000, large: 300_000, mmorpg: 600_000 },
    devPointsAdded: 20,
    benefitScore: 8,
    prerequisites: ['basic-physics'],
    startsUnlocked: false,
  },
  {
    id: 'save-to-cloud',
    name: 'Save to Cloud',
    category: 'engine',
    group: 'engine-save',
    tier: 2,
    researchCost: { rp: 15, money: 40_000 },
    engineCost: 30_000,
    gameCostBySize: { small: 10_000, medium: 20_000, large: 30_000, mmorpg: 60_000 },
    devPointsAdded: 5,
    benefitScore: 2,
    prerequisites: ['save-game'],
    startsUnlocked: false,
  },
  {
    id: 'mmo-support',
    name: 'MMO Support',
    category: 'engine',
    group: 'engine-multiplayer',
    tier: 3,
    researchCost: { rp: 150, money: 600_000 },
    engineCost: 180_000,
    gameCostBySize: { small: 150_000, medium: 300_000, large: 450_000, mmorpg: 900_000 },
    devPointsAdded: 30,
    benefitScore: 10,
    prerequisites: ['online-play'],
    startsUnlocked: false,
  },

  // ----------------------------------------------------------
  // Gameplay
  // ----------------------------------------------------------
  {
    id: 'game-tutorials',
    name: 'Game Tutorials',
    category: 'gameplay',
    group: 'gameplay-tutorials',
    tier: 1,
    researchCost: { rp: 0, money: 0 },
    engineCost: 30_000,
    gameCostBySize: { small: 10_000, medium: 20_000, large: 30_000, mmorpg: 60_000 },
    devPointsAdded: 3,
    benefitScore: 2,
    prerequisites: [],
    startsUnlocked: true,
  },
  {
    id: 'better-ux',
    name: 'Better User Experience',
    category: 'gameplay',
    group: 'gameplay-ux',
    tier: 1,
    researchCost: { rp: 15, money: 40_000 },
    engineCost: 30_000,
    gameCostBySize: { small: 10_000, medium: 20_000, large: 30_000, mmorpg: 60_000 },
    devPointsAdded: 5,
    benefitScore: 2,
    prerequisites: ['game-tutorials'],
    startsUnlocked: false,
  },
  {
    id: 'achievements',
    name: 'Achievements',
    category: 'gameplay',
    group: 'gameplay-achievements',
    tier: 1,
    researchCost: { rp: 15, money: 40_000 },
    engineCost: 30_000,
    gameCostBySize: { small: 10_000, medium: 20_000, large: 30_000, mmorpg: 60_000 },
    devPointsAdded: 5,
    benefitScore: 2,
    prerequisites: ['better-ux'],
    startsUnlocked: false,
  },
  {
    id: 'character-progression',
    name: 'Character Progression',
    category: 'gameplay',
    group: 'gameplay-progression',
    tier: 1,
    researchCost: { rp: 40, money: 120_000 },
    engineCost: 50_000,
    gameCostBySize: { small: 30_000, medium: 60_000, large: 90_000, mmorpg: 180_000 },
    devPointsAdded: 10,
    benefitScore: 4,
    prerequisites: ['better-ux'],
    startsUnlocked: false,
  },
  {
    id: 'skill-trees',
    name: 'Skill Trees',
    category: 'gameplay',
    group: 'gameplay-progression',
    tier: 2,
    researchCost: { rp: 80, money: 240_000 },
    engineCost: 100_000,
    gameCostBySize: { small: 60_000, medium: 120_000, large: 180_000, mmorpg: 360_000 },
    devPointsAdded: 15,
    benefitScore: 6,
    prerequisites: ['character-progression'],
    startsUnlocked: false,
  },
  {
    id: 'cooperative-play',
    name: 'Cooperative Play',
    category: 'gameplay',
    group: 'gameplay-coop',
    tier: 1,
    researchCost: { rp: 100, money: 400_000 },
    engineCost: 140_000,
    gameCostBySize: { small: 100_000, medium: 200_000, large: 300_000, mmorpg: 600_000 },
    devPointsAdded: 20,
    benefitScore: 8,
    prerequisites: ['skill-trees'],
    startsUnlocked: false,
  },

  // ----------------------------------------------------------
  // Dialogues
  // ----------------------------------------------------------
  {
    id: 'better-dialogue',
    name: 'Better Dialogue',
    category: 'dialogues',
    group: 'dialogue-core',
    tier: 1,
    researchCost: { rp: 10, money: 20_000 },
    engineCost: 10_000,
    gameCostBySize: { small: 5_000, medium: 10_000, large: 15_000, mmorpg: 30_000 },
    devPointsAdded: 3,
    benefitScore: 1,
    prerequisites: [],
    startsUnlocked: false,
  },
  {
    id: 'dialogue-tree',
    name: 'Dialogue Tree',
    category: 'dialogues',
    group: 'dialogue-core',
    tier: 2,
    researchCost: { rp: 40, money: 120_000 },
    engineCost: 50_000,
    gameCostBySize: { small: 30_000, medium: 60_000, large: 90_000, mmorpg: 180_000 },
    devPointsAdded: 8,
    benefitScore: 4,
    prerequisites: ['better-dialogue'],
    startsUnlocked: false,
  },
  {
    id: 'voice-over',
    name: 'Voice Over',
    category: 'dialogues',
    group: 'dialogue-voice',
    tier: 1,
    researchCost: { rp: 80, money: 240_000 },
    engineCost: 100_000,
    gameCostBySize: { small: 60_000, medium: 120_000, large: 180_000, mmorpg: 360_000 },
    devPointsAdded: 15,
    benefitScore: 6,
    prerequisites: ['dialogue-tree'],
    startsUnlocked: false,
  },
  {
    id: 'simple-body-language',
    name: 'Simple Body Language',
    category: 'dialogues',
    group: 'dialogue-body',
    tier: 1,
    researchCost: { rp: 80, money: 240_000 },
    engineCost: 100_000,
    gameCostBySize: { small: 60_000, medium: 120_000, large: 180_000, mmorpg: 360_000 },
    devPointsAdded: 12,
    benefitScore: 6,
    prerequisites: ['dialogue-tree'],
    startsUnlocked: false,
  },
  {
    id: 'advanced-body-language',
    name: 'Advanced Body Language',
    category: 'dialogues',
    group: 'dialogue-body',
    tier: 2,
    researchCost: { rp: 100, money: 400_000 },
    engineCost: 140_000,
    gameCostBySize: { small: 100_000, medium: 200_000, large: 300_000, mmorpg: 600_000 },
    devPointsAdded: 18,
    benefitScore: 8,
    prerequisites: ['simple-body-language'],
    startsUnlocked: false,
  },
  {
    id: 'celebrity-voice-acting',
    name: 'Celebrity Voice Acting',
    category: 'dialogues',
    group: 'dialogue-voice',
    tier: 2,
    researchCost: { rp: 80, money: 240_000 },
    engineCost: 100_000,
    gameCostBySize: { small: 60_000, medium: 120_000, large: 180_000, mmorpg: 360_000 },
    devPointsAdded: 15,
    benefitScore: 6,
    prerequisites: ['voice-over'],
    startsUnlocked: false,
  },
  {
    id: 'realistic-body-language',
    name: 'Realistic Body Language',
    category: 'dialogues',
    group: 'dialogue-body',
    tier: 3,
    researchCost: { rp: 150, money: 600_000 },
    engineCost: 180_000,
    gameCostBySize: { small: 150_000, medium: 300_000, large: 450_000, mmorpg: 900_000 },
    devPointsAdded: 25,
    benefitScore: 10,
    prerequisites: ['advanced-body-language'],
    startsUnlocked: false,
  },

  // ----------------------------------------------------------
  // Level Design
  // ----------------------------------------------------------
  {
    id: 'level-editor',
    name: 'Level Editor',
    category: 'levelDesign',
    group: 'level-editor',
    tier: 1,
    researchCost: { rp: 10, money: 20_000 },
    engineCost: 10_000,
    gameCostBySize: { small: 5_000, medium: 10_000, large: 15_000, mmorpg: 30_000 },
    devPointsAdded: 3,
    benefitScore: 1,
    prerequisites: [],
    startsUnlocked: false,
  },
  {
    id: 'easter-eggs',
    name: 'Easter Eggs',
    category: 'levelDesign',
    group: 'level-secrets',
    tier: 1,
    researchCost: { rp: 15, money: 40_000 },
    engineCost: 30_000,
    gameCostBySize: { small: 10_000, medium: 20_000, large: 30_000, mmorpg: 60_000 },
    devPointsAdded: 5,
    benefitScore: 2,
    prerequisites: ['level-editor'],
    startsUnlocked: false,
  },
  {
    id: 'mini-games',
    name: 'Mini Games',
    category: 'levelDesign',
    group: 'level-mini',
    tier: 1,
    researchCost: { rp: 40, money: 120_000 },
    engineCost: 50_000,
    gameCostBySize: { small: 30_000, medium: 60_000, large: 90_000, mmorpg: 180_000 },
    devPointsAdded: 8,
    benefitScore: 4,
    prerequisites: ['level-editor'],
    startsUnlocked: false,
  },
  {
    id: 'dynamic-environment',
    name: 'Dynamic Environment',
    category: 'levelDesign',
    group: 'level-dynamic',
    tier: 1,
    researchCost: { rp: 80, money: 240_000 },
    engineCost: 100_000,
    gameCostBySize: { small: 60_000, medium: 120_000, large: 180_000, mmorpg: 360_000 },
    devPointsAdded: 15,
    benefitScore: 6,
    prerequisites: ['mini-games'],
    startsUnlocked: false,
  },
  {
    id: 'no-loading-screens',
    name: 'No Loading Screens',
    category: 'levelDesign',
    group: 'level-loading',
    tier: 1,
    researchCost: { rp: 100, money: 400_000 },
    engineCost: 140_000,
    gameCostBySize: { small: 100_000, medium: 200_000, large: 300_000, mmorpg: 600_000 },
    devPointsAdded: 20,
    benefitScore: 8,
    prerequisites: ['dynamic-environment'],
    startsUnlocked: false,
  },

  // ----------------------------------------------------------
  // World Design
  // ----------------------------------------------------------
  {
    id: 'open-world',
    name: 'Open World',
    category: 'worldDesign',
    group: 'world-scope',
    tier: 1,
    researchCost: { rp: 15, money: 40_000 },
    engineCost: 30_000,
    gameCostBySize: { small: 10_000, medium: 20_000, large: 30_000, mmorpg: 60_000 },
    devPointsAdded: 8,
    benefitScore: 2,
    prerequisites: [],
    startsUnlocked: false,
  },
  {
    id: 'day-night-cycle',
    name: 'Day & Night Cycle',
    category: 'worldDesign',
    group: 'world-time',
    tier: 1,
    researchCost: { rp: 15, money: 40_000 },
    engineCost: 30_000,
    gameCostBySize: { small: 10_000, medium: 20_000, large: 30_000, mmorpg: 60_000 },
    devPointsAdded: 5,
    benefitScore: 2,
    prerequisites: [],
    startsUnlocked: false,
  },
  {
    id: 'rich-backstory',
    name: 'Rich Backstory',
    category: 'worldDesign',
    group: 'world-lore',
    tier: 1,
    researchCost: { rp: 15, money: 40_000 },
    engineCost: 30_000,
    gameCostBySize: { small: 10_000, medium: 20_000, large: 30_000, mmorpg: 60_000 },
    devPointsAdded: 5,
    benefitScore: 2,
    prerequisites: [],
    startsUnlocked: false,
  },
  {
    id: 'virtual-economy',
    name: 'Virtual Economy',
    category: 'worldDesign',
    group: 'world-economy',
    tier: 1,
    researchCost: { rp: 40, money: 120_000 },
    engineCost: 50_000,
    gameCostBySize: { small: 30_000, medium: 60_000, large: 90_000, mmorpg: 180_000 },
    devPointsAdded: 10,
    benefitScore: 4,
    prerequisites: ['open-world'],
    startsUnlocked: false,
  },
  {
    id: 'realistic-weather',
    name: 'Realistic Weather',
    category: 'worldDesign',
    group: 'world-weather',
    tier: 1,
    researchCost: { rp: 80, money: 240_000 },
    engineCost: 100_000,
    gameCostBySize: { small: 60_000, medium: 120_000, large: 180_000, mmorpg: 360_000 },
    devPointsAdded: 15,
    benefitScore: 6,
    prerequisites: ['day-night-cycle'],
    startsUnlocked: false,
  },
  {
    id: 'dynamic-world',
    name: 'Dynamic World',
    category: 'worldDesign',
    group: 'world-scope',
    tier: 2,
    researchCost: { rp: 100, money: 400_000 },
    engineCost: 140_000,
    gameCostBySize: { small: 100_000, medium: 200_000, large: 300_000, mmorpg: 600_000 },
    devPointsAdded: 20,
    benefitScore: 8,
    prerequisites: ['open-world', 'realistic-weather'],
    startsUnlocked: false,
  },

  // ----------------------------------------------------------
  // AI
  // ----------------------------------------------------------
  {
    id: 'better-ai',
    name: 'Better A.I.',
    category: 'ai',
    group: 'ai-core',
    tier: 1,
    researchCost: { rp: 40, money: 120_000 },
    engineCost: 50_000,
    gameCostBySize: { small: 30_000, medium: 60_000, large: 90_000, mmorpg: 180_000 },
    devPointsAdded: 8,
    benefitScore: 4,
    prerequisites: [],
    startsUnlocked: false,
  },
  {
    id: 'ai-companions',
    name: 'A.I. Companions',
    category: 'ai',
    group: 'ai-companions',
    tier: 1,
    researchCost: { rp: 40, money: 120_000 },
    engineCost: 50_000,
    gameCostBySize: { small: 30_000, medium: 60_000, large: 90_000, mmorpg: 180_000 },
    devPointsAdded: 10,
    benefitScore: 4,
    prerequisites: ['better-ai'],
    startsUnlocked: false,
  },
  {
    id: 'self-learning-ai',
    name: 'Self-Learning A.I.',
    category: 'ai',
    group: 'ai-core',
    tier: 2,
    researchCost: { rp: 150, money: 600_000 },
    engineCost: 180_000,
    gameCostBySize: { small: 150_000, medium: 300_000, large: 450_000, mmorpg: 900_000 },
    devPointsAdded: 25,
    benefitScore: 10,
    prerequisites: ['ai-companions'],
    startsUnlocked: false,
  },
];

// ============================================================
// Lookup Helpers
// ============================================================

const FEATURE_MAP = new Map<string, EngineFeatureDef>(
  ENGINE_FEATURES.map((f) => [f.id, f])
);

export function getFeatureDef(featureId: string): EngineFeatureDef | undefined {
  return FEATURE_MAP.get(featureId);
}

export function getFeaturesByCategory(category: EngineFeatureCategory): EngineFeatureDef[] {
  return ENGINE_FEATURES.filter((f) => f.category === category);
}

export function getStartingUnlockedFeatures(): string[] {
  return ENGINE_FEATURES.filter((f) => f.startsUnlocked).map((f) => f.id);
}

export function canResearchFeature(
  featureId: string,
  unlockedFeatures: string[]
): boolean {
  const def = FEATURE_MAP.get(featureId);
  if (!def) return false;
  if (def.startsUnlocked) return false;
  if (unlockedFeatures.includes(featureId)) return false;
  return def.prerequisites.every((prereq) => unlockedFeatures.includes(prereq));
}

export function canAddFeatureToEngine(
  featureId: string,
  engineFeatures: string[],
  unlockedFeatures: string[]
): { allowed: boolean; reason?: string } {
  const def = FEATURE_MAP.get(featureId);
  if (!def) return { allowed: false, reason: 'Feature not found' };
  if (!unlockedFeatures.includes(featureId)) return { allowed: false, reason: 'Not yet researched' };
  if (engineFeatures.includes(featureId)) return { allowed: false, reason: 'Already added' };

  const conflicting = engineFeatures.find((existingId) => {
    const existing = FEATURE_MAP.get(existingId);
    return existing && existing.category === def.category && existing.group === def.group;
  });
  if (conflicting) {
    const conflictDef = FEATURE_MAP.get(conflicting)!;
    return { allowed: false, reason: `Conflicts with ${conflictDef.name} (same group)` };
  }

  return { allowed: true };
}

export function getEngineDevPointsAdded(engineFeatures: string[]): Record<EngineFeatureCategory, number> {
  const result: Record<string, number> = {
    engine: 0, gameplay: 0, storyQuests: 0,
    dialogues: 0, levelDesign: 0, ai: 0,
    worldDesign: 0, graphics: 0, sound: 0,
  };
  for (const fid of engineFeatures) {
    const def = FEATURE_MAP.get(fid);
    if (def) result[def.category] += def.devPointsAdded;
  }
  return result as Record<EngineFeatureCategory, number>;
}

export function getEngineTotalBenefit(engineFeatures: string[]): number {
  let total = 0;
  for (const fid of engineFeatures) {
    const def = FEATURE_MAP.get(fid);
    if (def) total += def.benefitScore;
  }
  return total;
}

export const ENGINE_NAMES = [
  'Aurora Engine', 'Nebula Core', 'Titan Framework', 'Prism Engine',
  'Forge Runtime', 'Zenith Core', 'Vortex Engine', 'Apex Framework',
  'Nova Engine', 'Eclipse Core',
] as const;
