export const STUDIO_NAMES = [
  'Pixel Forge', 'Neon Arcade Studios', 'Binary Dreams', 'Obsidian Moon Games',
  'Jade Rabbit Interactive', 'Voltage Software', 'Ironclad Studios',
  'Crystal Dynamics West', 'Nebula Works', 'Starbound Interactive',
  'Cipher Games', 'Ember Studios', 'Frostbyte Entertainment',
  'Galactic Penguin', 'Helix Digital', 'Ion Storm West',
  'Kairos Games', 'Lunar Byte Studios', 'Mosaic Interactive',
  'Nimbus Games', 'Onyx Path Digital', 'Prism Studios',
  'Quantum Leap Games', 'Raven Soft', 'Sapphire Coast Studios',
  'Thunder Lotus West', 'Umbra Interactive', 'Vortex Games',
  'Wildcard Studios', 'Xenon Interactive', 'Zenith Digital',
  'Arc System Labs', 'Blueshift Games', 'Comet Trail Studios',
  'Dusk Light Interactive', 'Echo Point Games', 'Firewall Studios',
  'Gridlock Games', 'Horizon Craft', 'Infinite Loop Studios',
  'Jetstream Games', 'Keystone Interactive', 'Lighthouse Labs',
  'Meridian Games', 'Nova Core Studios', 'Orbit Entertainment',
  'Parallax Studios', 'Quartz Games', 'Redshift Interactive',
  'Solstice Studios', 'Titan Forge Games', 'Unity Point Studios',
  'Vector Games', 'Warp Drive Studios', 'Axiom Interactive',
  'Bastion Digital', 'Catalyst Games', 'Delta Force Studios',
  'Eclipse Games', 'Frontier Digital', 'Genesis Studios',
  'Havoc Interactive', 'Impulse Games', 'Junction Studios',
  'Kinetic Games', 'Labyrinth Studios', 'Monolith West',
  'Nexus Point Games', 'Omega Studios', 'Pinnacle Games',
  'Retro Rocket Studios', 'Summit Interactive', 'Tidal Games',
  'Ultraviolet Studios', 'Vertex Games', 'Wavelength Interactive',
  'Zephyr Studios', 'Afterburner Games', 'Blackthorn Studios',
  'Clockwork Games', 'Dragonfly Interactive', 'Evergreen Studios',
  'Foxhole Games', 'Glacier Interactive', 'Hardline Studios',
  'Indie Machine', 'Jackrabbit Games', 'Kraken Studios',
  'Lantern Games', 'Mammoth Interactive', 'Nightfall Studios',
  'Obelisk Games', 'Phoenix Rising Studios', 'Quicksilver Games',
  'Runestone Studios', 'Stardust Interactive', 'Tempest Games',
  'Underdog Studios', 'Vagabond Games', 'Windmill Interactive',
] as const;

export const GAME_NAMES = [
  'Crimson Odyssey', 'Neon Horizon', 'The Last Bastion', 'Starfall Legacy',
  'Dungeon Depths', 'Shadow Protocol', 'Cosmic Drift',
  'Iron Resolve', 'Crystal Caverns', 'Dragon Epoch',
  'Phantom Circuit', 'Void Walker', 'Emerald Quest',
  'Titan Fall Zero', 'Silent Frontier', 'Blazing Sands',
  'Cybernova', 'Frost Empire', 'Golden Saga',
  'Hex Grid Wars', 'Infernal Reign', 'Jade Dynasty Online',
  'Knightfall', 'Lunar Descent', 'Mech Overlords',
  'Nether Realms', 'Omega Protocol', 'Primal Instinct',
  'Quantum Break Zero', 'Rune Forged', 'Sky Pirates',
  'Thunder Plains', 'Underworld Rising', 'Viper Strike',
  'Warlords of Aethon', 'Xenoblade Dreams', 'Yonder Wilds',
  'Zero Gravity', 'Ancient Echoes', 'Bloodmoon Rising',
  'Chrono Shift', 'Dark Tides', 'Elemental Storm',
  'Fate Breaker', 'Ghost Recon Omega', 'Hollow Knight Zero',
  'Isle of Shadows', 'Jungle Warfare', 'Kingdom Ascent',
  'Lost Horizon', 'Mystic Forge', 'Night Runners',
  'Outland Express', 'Power Grid', 'Quest for Avalon',
  'Rift Walkers', 'Solar Winds', 'The Architect',
  'Ultra Combat', 'Vendetta Online', 'Warp Zone',
  'Apex Legends Zero', 'Biome Shift', 'Code Vanguard',
  'Dread Fortress', 'Eclipse Protocol', 'Flux Capacity',
  'Grim Frontier', 'Hyper Rally', 'Impact Zone',
  'Junkyard Titans', 'Karma Engine', 'Labyrinth Eternal',
  'Mirage Protocol', 'Nexus Wars', 'Operation Sandstorm',
  'Project Chimera', 'Rebel Galaxy Zero', 'Stormbreak',
  'Terranova', 'Uplink Protocol', 'Valkyrie Rising',
  'Warpath Chronicles', 'Xeno Colony', 'Year Zero',
  'Zenith Protocol', 'Arcane Legends', 'Battle Forge',
  'Catalyst Rising', 'Dawnbreaker', 'Eternal Frontier',
  'Firewatch Zero', 'Gladiator Kings', 'Horizon Chase',
  'Iron Kingdoms', 'Jet Set Infinity', 'King of Ruins',
  'Legacy of Ash', 'Midnight Sun', 'Nova Strike',
  'Orbital Decay', 'Pixel Dungeon X', 'Rogue Signal',
] as const;

export function randomStudioName(): string {
  return STUDIO_NAMES[Math.floor(Math.random() * STUDIO_NAMES.length)];
}

export function randomGameName(): string {
  return GAME_NAMES[Math.floor(Math.random() * GAME_NAMES.length)];
}
