import type { UpgradeNode } from '@/lib/game/types';

export const SKILL_TREE: UpgradeNode[] = [
  // ============================================================
  // Studio Upgrades (persist across games)
  // ============================================================

  // Tier 1
  {
    id: 'better-marketing',
    name: 'Better Marketing',
    description: 'Increase game sale rate by 15%',
    category: 'studio',
    tier: 1,
    prerequisites: [],
    cost: 3_000,
    researchCost: 5,
    effects: [{ type: 'saleRateMultiplier', value: 1.15 }],
  },
  {
    id: 'efficient-ops',
    name: 'Efficient Operations',
    description: 'Reduce server costs by 10%',
    category: 'studio',
    tier: 1,
    prerequisites: [],
    cost: 2_500,
    researchCost: 3,
    effects: [{ type: 'serverCostMultiplier', value: 0.90 }],
  },
  {
    id: 'basic-qa',
    name: 'Basic QA Process',
    description: 'Reduce bug encounter rate by 15%',
    category: 'studio',
    tier: 1,
    prerequisites: [],
    cost: 2_000,
    researchCost: 4,
    effects: [{ type: 'bugRateMultiplier', value: 0.85 }],
  },

  // Tier 2
  {
    id: 'viral-launch',
    name: 'Viral Launch Campaign',
    description: 'Increase peak player spike by 30%',
    category: 'studio',
    tier: 2,
    prerequisites: ['better-marketing'],
    cost: 8_000,
    researchCost: 10,
    effects: [{ type: 'peakPlayerMultiplier', value: 1.30 }],
  },
  {
    id: 'datacenter-unlocked',
    name: 'Data Center License',
    description: 'Unlock the ability to build your own data centers',
    category: 'studio',
    tier: 2,
    prerequisites: ['efficient-ops'],
    cost: 10_000,
    researchCost: 15,
    effects: [{ type: 'unlockDatacenters', value: 1 }],
  },
  {
    id: 'console-publishing',
    name: 'Console Publishing Deal',
    description: 'Unlock Console platform for game releases',
    category: 'studio',
    tier: 2,
    prerequisites: ['better-marketing'],
    cost: 12_000,
    researchCost: 12,
    effects: [{ type: 'unlockPlatform', value: 1 }],
  },
  {
    id: 'mobile-publishing',
    name: 'Mobile Publishing Deal',
    description: 'Unlock Mobile platform for game releases',
    category: 'studio',
    tier: 2,
    prerequisites: ['better-marketing'],
    cost: 8_000,
    researchCost: 8,
    effects: [{ type: 'unlockPlatform', value: 1 }],
  },

  // Tier 3
  {
    id: 'global-reach',
    name: 'Global Reach',
    description: 'Reduce region unlock costs by 40%',
    category: 'studio',
    tier: 3,
    prerequisites: ['viral-launch', 'datacenter-unlocked'],
    cost: 20_000,
    researchCost: 25,
    effects: [{ type: 'regionUnlockCostMultiplier', value: 0.60 }],
  },
  {
    id: 'studio-brand',
    name: 'Studio Brand Power',
    description: 'Increase studio fan conversion rate by 25%',
    category: 'studio',
    tier: 3,
    prerequisites: ['viral-launch'],
    cost: 15_000,
    researchCost: 20,
    effects: [{ type: 'studioFanConversionMultiplier', value: 1.25 }],
  },
  {
    id: 'server-optimization',
    name: 'Server Optimization',
    description: 'Reduce all server costs by an additional 20%',
    category: 'studio',
    tier: 3,
    prerequisites: ['datacenter-unlocked'],
    cost: 12_000,
    researchCost: 18,
    effects: [{ type: 'serverCostMultiplier', value: 0.80 }],
  },

  // ============================================================
  // Game Upgrades (unlocked per game)
  // ============================================================

  // Tier 1
  {
    id: 'bug-squasher',
    name: 'Bug Squasher',
    description: 'Reduce bug encounter rate by 25% for this game',
    category: 'game',
    tier: 1,
    prerequisites: [],
    cost: 1_500,
    researchCost: 3,
    effects: [{ type: 'bugRateMultiplier', value: 0.75 }],
  },
  {
    id: 'premium-pricing',
    name: 'Premium Pricing',
    description: 'Increase game sale price by 25%',
    category: 'game',
    tier: 1,
    prerequisites: [],
    cost: 2_000,
    researchCost: 4,
    effects: [{ type: 'priceMultiplier', value: 1.25 }],
  },
  {
    id: 'early-access',
    name: 'Early Access Program',
    description: 'Gain 20% more fans during growth phase',
    category: 'game',
    tier: 1,
    prerequisites: [],
    cost: 1_000,
    researchCost: 2,
    effects: [{ type: 'growthFanMultiplier', value: 1.20 }],
  },

  // Tier 2
  {
    id: 'bundle-deal',
    name: 'Bundle Deal',
    description: '30% chance to sell 2 copies when selling 1',
    category: 'game',
    tier: 2,
    prerequisites: ['premium-pricing'],
    cost: 5_000,
    researchCost: 8,
    effects: [{ type: 'doubleSaleChance', value: 0.30 }],
  },
  {
    id: 'dlc-pipeline',
    name: 'DLC Pipeline',
    description: 'Unlock the ability to create DLC content',
    category: 'game',
    tier: 2,
    prerequisites: ['early-access'],
    cost: 4_000,
    researchCost: 6,
    effects: [{ type: 'unlockDLC', value: 1 }],
  },
  {
    id: 'community-manager',
    name: 'Community Manager',
    description: 'Slow player decline rate by 20%',
    category: 'game',
    tier: 2,
    prerequisites: ['early-access'],
    cost: 3_000,
    researchCost: 5,
    effects: [{ type: 'declineRateMultiplier', value: 0.80 }],
  },

  // Tier 3
  {
    id: 'sequel-hype',
    name: 'Sequel Hype Machine',
    description: '50% launch boost for your next game from this game\'s fans',
    category: 'game',
    tier: 3,
    prerequisites: ['bundle-deal', 'dlc-pipeline'],
    cost: 10_000,
    researchCost: 15,
    effects: [{ type: 'sequelLaunchBoost', value: 1.50 }],
  },
  {
    id: 'esports-ready',
    name: 'Esports Ready',
    description: 'Double peak phase duration',
    category: 'game',
    tier: 3,
    prerequisites: ['community-manager'],
    cost: 8_000,
    researchCost: 12,
    effects: [{ type: 'peakDurationMultiplier', value: 2.0 }],
  },
];
